env:
  MAVEN_ARGS: "-T 8 -Dsingularity.jar.name.format=\\${project.artifactId} -Dgpg.skip=true -DforkCount=2C"
  SET_VERSION_OVERRIDE: "0.19.0-$GIT_BRANCH-SNAPSHOT"

buildResources:
  cpus: 8
  memoryMb: 10240

