CREATE TABLE requestHistory (
  requestId VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT '1971-01-01 00:00:01',
  requestState ENUM('CREATED', 'UPDATED', 'DELETING', 'DELETED', 'PAUSED', 'UNPAUSED', 'ENTERED_COOLDOWN', 'EXITED_COOLDOWN', 'FINISHED', 'DEPLOYED_TO_UNPAUSE', 'BOUNCED', 'SCALED', 'SCALE_REVERTED') NOT NULL,
  user VARCHAR(100) NULL,
  request BLOB DEFAULT NULL,
  json TEXT NULL,
  message VARCHAR(280) NULL,
  PRIMARY KEY (requestId, createdAt),
);

CREATE TABLE deployHistory (
  requestId VARCHAR(100) NOT NULL,
  deployId VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT '1971-01-01 00:00:01',
  user VARCHAR(100) NULL,
  deployStateAt TIMESTAMP NOT NULL DEFAULT '1971-01-01 00:00:01',
  deployState ENUM('SUCCEEDED', 'FAILED_INTERNAL_STATE', 'CANCELING', 'WAITING', 'OVERDUE', 'FAILED', 'CANCELED') NOT NULL,
  bytes BLOB DEFAULT NULL,
  json TEXT NULL,
  message VARCHAR(280) NULL,
  PRIMARY KEY (requestId, deployId),
);

CREATE TABLE taskHistory (
  taskId VARCHAR(200) NOT NULL,
  requestId VARCHAR(100) NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT '1971-01-01 00:00:01',
  lastTaskStatus ENUM('TASK_LAUNCHED', 'TASK_STAGING', 'TASK_STARTING', 'TASK_RUNNING', 'TASK_CLEANING', 'TASK_KILLING', 'TASK_FINISHED', 'TASK_FAILED', 'TASK_KILLED', 'TASK_LOST', 'TASK_LOST_WHILE_DOWN', 'TASK_ERROR', 'TASK_DROPPED', 'TASK_GONE', 'TASK_UNREACHABLE', 'TASK_GONE_BY_OPERATOR', 'TASK_UNKNOWN') NOT NULL,
  bytes BLOB DEFAULT NULL,
  json TEXT NULL,
  runId VARCHAR(100) NULL,
  deployId VARCHAR(100) NULL,
  host VARCHAR(100) NULL,
  startedAt TIMESTAMP NULL,
  purged BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (taskId),
);
