zk:
  image: bobrik/zookeeper
  net: host
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: 1

master:
  image: mesosphere/mesos-master:1.1.1
  net: host
  environment:
    MESOS_ZK: zk://localhost:2181/mesos
    MESOS_HOSTNAME: localhost
    MESOS_IP: 127.0.0.1
    MESOS_QUORUM: 1
    MESOS_CLUSTER: docker-compose
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_ROLES: "OPS"

slave:
  image: hubspot/singularityexecutorslave:0.18.0-SNAPSHOT
  command: mesos-slave
  net: host
  environment:
    MESOS_MASTER: zk://localhost:2181/mesos
    MESOS_HOSTNAME: localhost
    MESOS_IP: 127.0.0.1
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_ROLES: "OPS"
    MESOS_RESOURCES: "cpus(OPS):1;cpus(*):1;mem(OPS):512;mem(*):1024"
    MESOS_ATTRIBUTES: "example:value;myNumber:1"
    MESOS_ISOLATION: cgroups/cpu,cgroups/mem
    MESOS_WORK_DIR: /var/lib/mesos/agent
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /sys:/sys

scheduler:
  image: hubspot/singularityservice:0.18.0-SNAPSHOT
  net: host
  environment:
    - DOCKER_HOST
    - LOAD_BALANCER_URI=http://localhost:8080/baragon/v2/request
    - SINGULARITY_SMTP_HOST=localhost
    - SINGULARITY_SMTP_PORT=1025
    - SINGULARITY_MESOS_FRAMEWORK_ROLE=OPS

baragonservice:
  image: hubspot/baragonservice:0.5.0
  net: host
  environment:
    - DOCKER_HOST
    - BARAGON_PORT=8080
    - BARAGON_UI_BASE=/baragon/v2

baragonagent:
  image: hubspot/baragonagent:0.5.0
  net: host
  environment:
    NGINX_PORT: 80
    BARAGON_PORT: 8882
    BARAGON_AGENT_GROUP: test

mailhog:
  image: mailhog/mailhog
  net: host
