cache:
  - ./node_modules

before:
  - description: Pull down and Configure the variables for our Singularity Deployment
    commands:
       - git clone git@git.hubteam.com:HubSpot/SingularityBuildConfig.git custom-build-config
       - custom-build-config/setup-ui-env.py

after:
  onSuccess:
    - description:
      name: copyindex
      commands:
        - cp dist/index.html dist/static/index.html
    - description:
      name: publish
      activeByDefault: false
      commands:
        - /bin/bash custom-build-config/publish-ui.sh

stepActivation:
  publish:
    branches: [hs_staging, hs_qa, hs_stable, master, build-on-blazar]

env:
  SET_VERSION_OVERRIDE: "0.21.0-$GIT_BRANCH-SNAPSHOT"
