# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if !Vagrant.has_plugin?("vagrant-hostsupdater")
    raise "Please install vagrant-hostsupdater via `vagrant plugin install vagrant-hostsupdater`"
  end

  config.vm.synced_folder "../", "/singularity", type: "nfs"

  config.vm.box = "singularity-develop-0.20.0"
  config.vm.box_url = "https://vagrantcloud.com/tpetr/boxes/singularity-develop-0.20.0/versions/1/providers/virtualbox.box"

  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

  private_ip = '192.168.33.11'
  mysql_password = "mesos7mysql"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.auto_detect = true
  end
  
  config.vm.hostname = 'vagrant-singularity'
  config.vm.network :private_network, ip: private_ip

  config.vm.define "test", primary: true do |test|
    test.vm.provision "shell", path: "provision-singularity.sh"
  end

  config.vm.define "develop", autostart: false
  
end


