module.exports =
    env: 'local'
    API_BASE: 'api.hubapiqa.com'
    APP_BASE: 'app.hubspotqa.com'
    LOGIN_BASE: 'login.hubspotqa.com'
    NAV_BASE: 'navqa.hubapi.com'
    STATIC_BASE: 'static.hubspotqa.com'
    INTERNAL_BASE: 'internal.hubapiqa.com'
    SINGULARITY_BASE: 'heliograph.iad01.hubspot-networks.net:7000'
    LOGIN_PORTAL: 99121841
