---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        cpus: 4
        memory: 1536
      network:
        - - private_network
          - ip: '192.168.33.10'

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[baragon::server]
      - recipe[nginx]
      - recipe[baragon::agent]
      - recipe[singularity::default]
    attributes:
      singularity:
        zk_hosts:
        - 'localhost:2181'
