name             'singularity'
maintainer       'Tom Petr'
maintainer_email 'tpetr@hubspot.com'
license          'All rights reserved'
description      'Installs Singularity dependencies (mesos, zk, mysql)'
version          '1.0.0'
supports         'ubuntu'

depends 'apt'
depends 'build-essential'
depends 'mysql', '6.0.13'
depends 'git'
depends 'mysql2_chef_gem'
depends 'database'
depends 'hostsfile'
depends 'java'
depends 'mesos', '~> 0.2'
depends 'openssl', '~> 3.0'
depends 'docker', '~> 0.36'
depends 'logrotate'
